config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#index"

  get 'about', to: 'pages#about'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 3, maximum: 50}
    validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:edit, :update, :destroy, :show]
    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def show
        set_article
    end

    def edit
        set_article
    end

    def update
        set_article
        if @article.update(article_params)
            flash[:notice] = "Article was updated"
            redirect_to article_path(@article)
        else
            flash[:notice] = "Article was not updated"
            render 'edit'
        end
    end

    def index
        @articles = Article.all
    end

    def destroy
        set_article
        @article.destroy
        flash[:notice] = "Article was deleted"
        redirect_to articles_path
    end
    
    private
    def article_params
        params.require(:article).permit(:title, :description)
    end

    def set_article
        @article = Article.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>
<%= form_for @article do |f| %>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>
<%= link_to 'Back', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<html>
<head>
<%= javascript_include_tag "application" %>
</head>
<body>
<h1>Welcome to Blog</h1>

<h2>Listing all articles</h2>
<p>
<%= link_to "Create new article", new_article_path %>
</p>
<table>
<tr>
<th>Title</th>
<th>Description</th>
</tr>

<% @articles.each do |article|%>
<tr>
<td><%= article.title %></td>
<td><%= article.description %></td>
<td><%= link_to 'Edit', edit_article_path(article) %></td>
<td><%= link_to 'Show', article_path(article) %></td>
<td><%= button_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure"} %></td>
</tr>
<% end%>

</table>
</body>
</html>

app/views/articles/new.html.erb
<h1>Create an article</h1>
<%= render 'form'%>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<p>
<%= link_to 'Back', articles_path %>
</p>

<h2>
<%= @article.title %>
</h2>
<p>
<%= @article.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

<% flash.each do |name, msg| %>
    <ul>
     <li><%= msg %></li>
    </ul>
<% end %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<html>
<body>
<h1>Welcome to Blog</h1>

<%= link_to 'About', about_path %>
</body>
</html>